spring:
  datasource:
    url: jdbc:mariadb://stg-yswa-kr-practice-db-master.mariadb.database.azure.com:3306/S07P11C203?serverTimezone=UTC&useUnicode=true&characterEncoding=utf8
    driver-class-name: org.mariadb.jdbc.Driver
    username: S07P11C203
    password: hhqiKzxIqy
#  mail:
#    host: smtp.gmail.com
#    port: 587
#      username: 본인의 구글 계정 @gmail.com
#    password: 본인의 구글 계정 비밀번호
#    properties:
#      mail.smtp.auth: true
#      mail.smtp.starttls.enable: true

  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
#  devtools:
#    livereload:
#      enabled: true

#logging:
#  level:
#    org:
#      springframework:
#        web: debug
#    sql: debug



