spring:
  datasource:
    url: jdbc:mariadb://stg-yswa-kr-practice-db-master.mariadb.database.azure.com:3306/S07P11C203?serverTimezone=UTC&useUnicode=true&characterEncoding=utf8
    driver-class-name: org.mariadb.jdbc.Driver
    username: S07P11C203
    password: hhqiKzxIqy
#  mail:
#    host: smtp.gmail.com
#    port: 587
#    username:
#    password:
#    properties:
#      mail.smtp.auth: true
#      mail.smtp.starttls.enable: true

  mail:
    properties:
      mail:
        smtp:
          starttls:
            enable: 'true'
          auth: 'true'
    host: smtp.gmail.com
    username: c203ssafy@gmail.com
    debug: 'true'
    password: riknhssmiejhjmom
    default:
      encoding: UTF-8
    port: '587'
    transport:
      protocol: smtp
    restart:
      enabled: true

  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
#  devtools:
#    livereload:
#      enabled: true

#logging:
#  level:
#    org:
#      springframework:
#        web: debug
#    sql: debug



